---
- name: "add cuda to default path"
  copy:
    src: etc/profile.d/cuda.sh
    dest: /etc/profile.d/cuda.sh
    mode: 0644
    owner: root
    group: root

- name: "docker: install nvidia runtime as default"
  copy:
    src: etc/docker/daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
    owner: root
    group: root
  notify:
    - "restart docker"

# this should be already created on JetPack
- name: "create docker group"
  group:
    name: docker
    state: present
  register: users

- name: "get list of existing users"
  getent:
    database: passwd
  tags:
    - users

- name: "add user 1000 to docker group"
  user:
    name: "{{ item.0 }}"
    groups:
      - docker
    append: True
  loop: "{{ getent_passwd.items() | list }}"
  when: item[1][1] | int == 1000
  tags:
    - users

- include: swap.yml
- include: software.yml
- include: autofs.yml
