---
#
#  Software that all hosts with this role will need
#
- name: install software for Jetson Nano
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-compose
  tags:
    - sw

- name: remove ubuntu-desktop
  apt:
    name: "ubuntu-desktop"
    state: absent
    autoremove: yes
    autoclean: yes
