---
- include: loadconfig.yml

# Gather facts specific to the Raspberry Pi platform
- include: raspi-facts.yml

- name: get rid of default 127.0.1.1 binding
  lineinfile:
    dest=/etc/hosts
    regexp="^127.0.1.1"
    state=absent

# Set X keyboard layout
- name: set X11 keyboard layout
  command: "raspi-config nonint do_configure_keyboard {{ xkblayout }}"
  when: "xkblayout|default(false) and linux_xkblayout != xkblayout"

# Set wifi country
- name: set wifi country
  command: "raspiconfig nonint do_wifi_country {{ wifi_country }}"
  when: "wifi_country|default(false) and wifi_country != raspi_wifi_country"

# Enable sshd
- name: disable ssh login for user pi
  lineinfile:
    dest=/etc/ssh/sshd_config
    line="DenyUsers pi"
    state=present
  tags:
    - raspi

- name: enable SSH via raspi-config
  shell: "raspi-config nonint do_ssh 0"
  when: not raspi_ssh_enabled
  tags:
    - raspi

# Other tasks
- include: software.yml
- include: users.yml
- include: raspi-config.yml
- include: darshan-dev.yml
  when: "darshan_dev|default(false)"

# Install motd
# May be easier to pull from /sys/firmware/devicetree/base/model
- name: load Raspberry Pi hardware history
  include_vars:
    file: vars/raspi-models.yml
  tags:
    - motd

- name: install motd
  template:
    src: etc/motd
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"
  tags:
    - motd

- include: ufw.yml
