---
timezone: "America/Los_Angeles"
locale: "en_US.UTF-8"
target_hostname: "clovermine"
target_domain: "local"
xkblayout: "us"
wifi_country: "US"
enable_gui: True
enable_autologin: False
enable_bootwait: False
enable_bootsplash: False
enable_camera: False
enable_vnc: False
enable_spi: False
enable_i2c: False
enable_serial: True
enable_serial_hw: True
enable_onewire: False
enable_rgpio: False
darshan_dev: True
host_software:
  - libncurses-dev      # for irssi
  - libperl-dev         # for irssi
  - libglib2.0-dev      # for irssi
