---
timezone: "America/Los_Angeles"
locale: "en_US.UTF-8"
swapsize_gb: 0      # set to 0 to disable play
systemd_default_target: multi-user
autofs: # remember to enable mount access from the filer side too
  - src: "synology.local:/volume1/glock"
    dest: "/synology"
    opts: "-retry=0,tcp,soft,rw,vers=3"
host_software:
  - python3-venv
  - python3-dev     # needed for many python packages built from source
  - python3-wheel   # for simplifying pip install
# for installing docker-compose from pypi
# - libffi-dev      # for pip install docker-compose
# - libssl-dev      # for pip install docker-compose
# - gfortran
# - gfortran-doc
